server:
  port: 8080
  servlet:
    context-path: /bishe
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  mail:
    username: verifysend@163.com
    password: UHBAGUCTCEJATZOD
    host: smtp.163.com
    port: 465
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true